-- Preenche modulos.descricao com o conteúdo oficial do Manual de Metodologia e
-- Módulos Raiz v3. Os 24 módulos (codigo, nome, pilar, fase) já estão alinhados
-- ao manual no banco; apenas a coluna descricao estava vazia (24/24).
-- Atualiza por codigo (chave estável usada pelo app), preservando os UUIDs e as
-- ligações em cliente_modulos.
--
-- ROLLBACK:
--   update public.modulos set descricao = null
--   where codigo in ('1.1','1.2','1.3','2.1','2.2','2.3','3.1','3.2','3.3',
--     '4.1','4.2','4.3','4.4','5.1','5.2','5.3','5.4','5.5','6.1','6.2','6.3',
--     '7.1','7.2','7.3');

update public.modulos set descricao = 'Define com precisão quem é o profissional no ambiente digital, para quem ele fala e por que é a escolha certa. Sem posicionamento claro, todo investimento em conteúdo e tráfego perde eficiência: o paciente não entende o diferencial e compara apenas por preço.' where codigo = '1.1';
update public.modulos set descricao = 'Estrutura a identidade visual e verbal do profissional nas redes sociais para transmitir autoridade, confiança e consistência. Uma marca sem identidade clara confunde o paciente e reduz a percepção de valor, tornando mais difícil justificar preços premium.' where codigo = '1.2';
update public.modulos set descricao = 'Transforma a produção de conteúdo em um sistema previsível e estratégico, alinhado à jornada do paciente. A ausência de planejamento editorial é a principal causa de publicações inconsistentes que não convertem, e de profissionais que produzem muito conteúdo sem resultado.' where codigo = '1.3';
update public.modulos set descricao = 'Antes de investir em qualquer canal de captação, é necessário entender o que está funcionando e o que não está. Este módulo audita todas as fontes de leads existentes e estabelece as métricas corretas para que decisões de investimento sejam tomadas com base em dados.' where codigo = '2.1';
update public.modulos set descricao = 'Entrega a inteligência estratégica completa para campanhas de tráfego pago em Meta Ads e Google Ads. A Raiz atua como consultora estratégica: define estrutura de funil, segmentação, KPIs e briefings de criativos. A execução operacional das campanhas é responsabilidade do gestor de tráfego ou agência contratada pelo cliente.' where codigo = '2.2';
update public.modulos set descricao = 'Conecta a atração de leads a um sistema de qualificação automatizada, garantindo que apenas pacientes com real potencial de conversão cheguem ao atendimento. Filtra, aquece e direciona o lead, reduzindo desperdício de tempo da equipe com contatos frios.' where codigo = '2.3';
update public.modulos set descricao = 'O primeiro contato define 80% da percepção de valor do paciente antes mesmo de ele chegar ao consultório. Atendimentos inconsistentes, demora na resposta e ausência de qualificação resultam em leads de baixa qualidade, alta taxa de no-show e agendamentos desmarcados.' where codigo = '3.1';
update public.modulos set descricao = 'A consulta é o momento de maior influência sobre a decisão do paciente, e a maioria dos profissionais a conduz como um evento clínico, não como uma venda consultiva. Este módulo estrutura a consulta para que o plano de tratamento seja apresentado com clareza, segurança e ancoragem de valor.' where codigo = '3.2';
update public.modulos set descricao = 'Entre 30% e 50% dos orçamentos apresentados em clínicas são perdidos por ausência de follow-up estruturado. Este módulo cria um sistema de acompanhamento pós-consulta que reativa leads frios e recupera orçamentos abandonados, sem depender de memória ou improviso da equipe.' where codigo = '3.3';
update public.modulos set descricao = 'Antes de qualquer ajuste, é preciso enxergar com clareza o que entra, o que sai e onde estão as perdas invisíveis. Este módulo realiza um levantamento completo da situação financeira atual, identificando custos ocultos, procedimentos deficitários e o verdadeiro ponto de equilíbrio.' where codigo = '4.1';
update public.modulos set descricao = 'Precificar sem método é um dos erros mais caros de uma clínica. Preços abaixo do necessário drenam margem mesmo com agenda cheia; preços sem estratégia afastam pacientes de alto valor. Este módulo constrói uma tabela de honorários baseada em custo real, posicionamento de mercado e percepção de valor.' where codigo = '4.2';
update public.modulos set descricao = 'Faturamento sem controle é ilusão de crescimento. Este módulo implementa ferramentas práticas de gestão financeira e cria uma rotina de acompanhamento que transforma o profissional em um gestor consciente de suas margens, sazonalidades e projeções.' where codigo = '4.3';
update public.modulos set descricao = 'Clínicas em crescimento acumulam exposições jurídicas e trabalhistas que passam despercebidas até se tornarem um problema caro. Este módulo não substitui assessoria jurídica ou contábil especializada: seu objetivo é mapear as principais áreas de risco para que o cliente tome decisões informadas.' where codigo = '4.4';
update public.modulos set descricao = 'Processos que existem apenas na cabeça do dono geram retrabalho, erros e dependência operacional permanente. Este módulo mapeia, documenta e padroniza os processos críticos da clínica, criando um sistema operacional que qualquer membro da equipe pode executar com consistência.' where codigo = '5.1';
update public.modulos set descricao = 'Uma equipe sem clareza de papéis gera conflitos, omissões e retrabalho, sobrecarregando o dono com operacional que deveria ser delegado. Este módulo estrutura responsabilidades, cria rituais de gestão eficientes e implanta indicadores de performance baseados em resultados.' where codigo = '5.2';
update public.modulos set descricao = 'Contratar errado é uma das perdas mais caras e silenciosas para uma clínica. A maioria dos processos seletivos é conduzida por intuição, sem critérios definidos, resultando em alta rotatividade e atendimentos inconsistentes com o posicionamento da marca.' where codigo = '5.3';
update public.modulos set descricao = 'A tecnologia usada de forma estratégica reduz esforço manual, elimina erros operacionais e libera tempo para atividades de maior valor. Este módulo audita as ferramentas atuais e implementa um ecossistema tecnológico enxuto e funcional.' where codigo = '5.4';
update public.modulos set descricao = 'A IA está transformando a operação de clínicas de saúde de forma acelerada. Ferramentas de atendimento automatizado, qualificação de leads com IA conversacional e análise preditiva de cancelamentos já estão disponíveis e acessíveis para clínicas de médio porte. Este módulo identifica e implementa os usos mais impactantes de IA na realidade de cada cliente.' where codigo = '5.5';
update public.modulos set descricao = 'A experiência do paciente começa antes do primeiro atendimento e se estende muito além da alta, mas a maioria das clínicas não gerencia conscientemente nenhuma das etapas. Este módulo estrutura a jornada completa com pontos de contato que geram encantamento e constroem lealdade.' where codigo = '6.1';
update public.modulos set descricao = 'Custa de 5 a 7 vezes mais conquistar um novo paciente do que reter um existente. Este módulo cria estruturas sistemáticas de acompanhamento pós-tratamento e reativação de pacientes inativos, transformando a base atual da clínica em uma fonte constante de receita recorrente.' where codigo = '6.2';
update public.modulos set descricao = 'Indicação é o canal de captação com menor custo e maior taxa de conversão, mas quase nenhuma clínica tem um sistema formal para gerar indicações com consistência. Este módulo cria uma estrutura que estimula, facilita e monitora o processo de indicação.' where codigo = '6.3';
update public.modulos set descricao = 'Expansão prematura é uma das principais causas de colapso de clínicas que pareciam estar crescendo. Este módulo avalia com precisão se o negócio está operacionalmente pronto para escalar, identificando os pré-requisitos que precisam estar consolidados antes de qualquer movimento.' where codigo = '7.1';
update public.modulos set descricao = 'Abrir uma segunda unidade ou trazer um sócio-operador sem estrutura é uma das apostas mais arriscadas no setor. Este módulo constrói o modelo de negócio completo para a expansão física e estrutura o papel de um sócio-operador de forma que o crescimento não dependa exclusivamente do fundador.' where codigo = '7.2';
update public.modulos set descricao = 'Crescer com qualidade exige que a operação funcione de forma consistente com ou sem a presença do fundador em cada unidade. Este módulo transforma o conhecimento tácito do dono em um modelo de gestão documentado, treinável e replicável.' where codigo = '7.3';
