// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaqiaxcdyfmzocsqucxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hcWlheGNkeWZtem9jc3F1Y3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2OTM0NTYsImV4cCI6MjA5MjI2OTQ1Nn0.NbjV1JHnmgiMzUvxFyCp2MeLS5sCr5SQh7XiXMZN6JE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});